export const questions = {
  "Persuader": "Overtuigen",
  "Détendre": "Relaxen",
  "Dessiner": "Tekenen",
  "Chanter": "Zingen",
  "Commencer": "Beginnen",
  "Prononcer": "Uitspreken",
  "Une chanteuse": "Een zangeres",
  "Un chanteur": "Een zanger",
  "Un dessin": "Een tekening",
  "Un rêve": "Een droom",
  "Un espoir": "Een hoop ",
  "Le monde": "De wereld",
  "Les applaudissements": "Het applaus",
  "Un manteau": "Een jas",
  "Un pneu": "Een band, een autoband",
  "Drôle": "Grappig",
  "Impressionnant": "Indrukwekkend",
  "Célèbre": "Beroemd",
  "Horrible": "Verschrikkelijk",
  "Ennuyant": "Vervelend",
  "Compliqué": "Ingewikkeld",
  "Innatendu": "Onverwacht",
  "Envoyer": "Verzenden",
  "Appuyer sur": "Duwen op",
  "Insérer": "Invoegen",
  "Rétablir": "Herstellen",
  "Allumer": "Aansteken",
  "Vérifier": "Nakijken",
  "Confirmer": "Bevestigen",
  "Souhaiter": "Wensen",
  "Ajouter": "Toevoegen",
  "Savoir": "Weten",
  "Démarrer": "Starten,Opstarten",
  "Essayer": "Proberen",
  "Aider": "Helpen",
  "Fermer": "sluiten",
  "Supprimer": "Verwijderen",
  "Devoir": "Moeten",
  "Télécharger": "Downloaden",
  "Répondre": "Antwoorden",
  "Trouver": "Vinden",
  "Pouvoir": "Kunnen,mogen",
  "Utiliser": "Gebruiken",
  "Voulior": "Willen",
  "Réussir": "Slagen",
  "Remplir": "Vullen",
  "Brancher": "Aansluiten",
  "Résouder": "Oplossen",
  "Vendre": "Verkopen",
  "Retirer": "Afnemen,Afpakken",
  "Rendre": "Teruggeven",
  "Connaître": "Kennen",
  "Posséder": "Bezitten",
};
